---
title: "intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r eval = TRUE}
read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t")
```

```{r eval = TRUE}
acacia <- read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t")
```

#Rescaling Axes

```{r}
acacia <- read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt",
         sep ="\t",
         na.strings = "dead")
is.numeric(acacia$HEIGHT)
head(acacia)
#View(acacia)
```

```{r}
library(ggplot2)
ggplot(data = acacia, mapping = aes(x = CIRC, y = HEIGHT)) +
geom_point(size = 3, color = "blue", alpha = 0.5) +
scale_y_log10() +
scale_x_log10()
```

#Fitting Linear Models
```{r}
ggplot(acacia, aes(x = CIRC, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()

ggplot(acacia, aes(x = CIRC, y = HEIGHT, color = TREATMENT, linetype = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()


ggplot(acacia, aes(x = CIRC, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth(method = "lm") # try with "glm"
```

#Histograms and Bar plots
```{r}
ggplot(data = acacia, mapping = aes(x = TREATMENT)) +
geom_bar()

ggplot(acacia, aes(x = CIRC)) +
geom_histogram(fill = "red")

ggplot(acacia, aes(x = CIRC, color = TREATMENT)) +
geom_histogram(bins = 20)

ggplot(acacia, aes(x = CIRC, fill = TREATMENT)) +
geom_histogram(bins = 20, color = "gray")
```

#Layering Data

```{r}
ggplot() +
geom_point(data = acacia,
           mapping = aes(x = CIRC, y = HEIGHT,
                         color = TREATMENT)) +
geom_smooth(data = acacia,
            mapping = aes(x = CIRC, y = HEIGHT))
ggplot() +
geom_point(data = acacia,
           mapping = aes(x = CIRC, y = HEIGHT,
                         color = TREATMENT)) +
geom_smooth(data = acacia,
            mapping = aes(x = CIRC, y = HEIGHT)) +
geom_histogram(data = acacia,
               mapping = aes(x = CIRC, color = TREATMENT),
               alpha = 0.1)

```

#Saving plots as image files
```{r}
ggsave("acacia_by_treatment.jpg")
ggsave("acacia_by_treatment.pdf", height = 5, width = 5)

```

#Scatterplots

```{r}
ggplot(data = acacia, mapping = aes(x = CIRC, y = AXIS1)) +
geom_point() +
labs(x = "Circumference", y = "Canopy Diameter", title = " UHURU Acacia Survey Data")

ggplot(data = acacia, mapping = aes(x = CIRC, y = AXIS1)) +
geom_point() +
scale_x_log10() + scale_y_log10() +
labs(x = "Circumference", y = "Canopy Diameter", title = "UHURU Acacia Survey Data")

ggplot(data = acacia, mapping = aes(x = CIRC, y = AXIS1, color = ANT)) +
geom_point() +
labs(x = "Circumference", y = "Canopy Diameter", title = "UHURU Acacia Survey Data")

ggplot(data = acacia, mapping = aes(x = CIRC, y = AXIS1, color = ANT)) +
geom_point() +
labs(x = "Circumference", y = "Canopy Diameter", title = "UHURU Acacia Survey Data") + facet_wrap(~ANT)

ggplot(data = acacia, mapping = aes(x = CIRC, y = AXIS1, color = ANT)) +
geom_point() +
labs(x = "Circumference", y = "Canopy Diameter", title = "UHURU Acacia Survey Data") + geom_smooth() +
facet_wrap(~ANT)
```

#Histograms

```{r}
ggplot(data = acacia, aes(x = ANT)) + geom_bar()
ggplot(data = acacia, mapping = aes(x = HEIGHT)) +
labs(x = "Height (m)", y = "Number of Acacia", title = "UHURU Acacia Survey Data")
geom_histogram()

ggplot()+
geom_histogram(data = acacia, mapping = aes(x = AXIS1), alpha = 0.3, color = "red") + geom_histogram(data = acacia, mapping = aes(x = AXIS2), alpha = 0.3, color = "black") +
labs(x = "Canopy Diameter (m)", y = "Number of Acacia", title = "UHURU Acacia Survey Data")

ggplot()+
geom_histogram(data = acacia, mapping = aes(x = AXIS1), alpha = 0.3, color = "red", bins = 10) + geom_histogram(data = acacia, mapping = aes(x = AXIS2), alpha = 0.3, color = "black", bins = 10) +
labs(x = "Canopy Diameter (m)", y = "Number of Acacia", title = "UHURU Acacia Survey Data") + facet_wrap(~~TREATMENT) + facet_wrap(~~TREATMENT)
```
